#ifndef MAP
#define MAP

#include <raylib.h>
#include <raymath.h>
#include <vector>
#include <queue>
#include "Room.hpp"
#include "Level.hpp"

// NOTE: the terms "cells" amd "rooms" can be used interchangeably here.
//       but if you want to be pedantic...
//       "cells" are squares in the map with no data
//       "rooms" are squares in the map with room data (e.g. room type, room tilemap)

class Map;

class Map {
  public:
    Level* level_info; // pointer to necessary level information
    int map_width; // in cells
    int map_height; // in cells
    int min_rooms = 10; // in cells
    int max_rooms = 20; // in cells
    float cell_width = 1280; // in pixels
    float cell_height = 768; // in pixels
    std::queue<Room*> checkable_rooms; // this contains the rooms that can still have neighbor rooms
    std::vector<Room*> all_rooms; // this contains all rooms generated by the map
    std::vector<std::vector<RoomType>> map; // this contains the layout of the map (in the form of a 2D array)
    Vector2 player_position; // TODO: create this after starting room is generated
    Vector2 enemy_position; // TODO: create this after boss room is generated
    Map(int width, int height);
    bool IsCellValidRoom(int x, int y);
    void CreateRoomInMap(Room* room);
    void GenerateStartRoom();
    void GenerateBetweenRooms();
    void GenerateEndRooms();
    void GenerateBossRoom();
    void SetUpRooms();
    void DrawMap();
    void DrawGrid();
};

#endif